name: "Build"

on:
  - "push"
  - "pull_request"

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        job_name: ["linux", "windows"]

        include:
          - job_name: "linux"
            os: "ubuntu-latest"
            shell: "bash {0}"

          - job_name: "windows"
            os: "windows-latest"
            shell: "msys2 {0}"

    defaults:
      run:
        shell: "${{ matrix.shell }}"

    name: "${{ matrix.job_name }}"
    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "msys2/setup-msys2@v2"
        if: "matrix.os == 'windows-latest'"
        with:
          path-type: "inherit"
          msystem: "MINGW64"
          update: true
          install: "mingw-w64-x86_64-gcc mingw-w64-x86_64-ninja mingw-w64-x86_64-pkg-config mingw-w64-x86_64-openssl mingw-w64-x86_64-zlib"

      - run: "choco install -y winfsp"
        if: "matrix.os == 'windows-latest'"
        shell: "powershell"

      - run: "sudo apt install -y libfuse3-dev libssl-dev zlib1g-dev"
        if: "matrix.os == 'ubuntu-latest'"

      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6

      - uses: "actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405" # v6
        with:
          python-version: "3.x"

      - run: "pip install meson ninja"

      - run: "meson setup --buildtype release build"
        if: "matrix.os == 'windows-latest'"

      - run: "meson setup --buildtype release build"
        if: "matrix.os != 'windows-latest'"
        env:
          CC: "gcc-14"

      - run: "meson compile -C build -v"

      - uses: "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a" # v7
        if: "matrix.os == 'windows-latest'"
        with:
          name: "fuse-fscrypt-${{ matrix.job_name }}"
          path: "build/fuse-fscrypt.exe"

      - uses: "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a" # v7
        if: "matrix.os != 'windows-latest'"
        with:
          name: "fuse-fscrypt-${{ matrix.job_name }}"
          path: "build/fuse-fscrypt"

      - uses: "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a" # v7
        if: "failure()"
        with:
          name: "compile-log"
          path: "build/meson-logs/meson-log.txt"
